### ISSUE TITLE
Script not working latest bareos with MariaDB 5.5.52

### ISSUE THREAD

**Issue by marcelmfs** [NETWAYS/check_bareos#18]
```
Traceback (most recent call last):
  File "./check_bareos.py", line 634, in <module>
    args.func(args)
  File "./check_bareos.py", line 581, in checkTape
    checkResult = checkEmptyTapes(cursor, args.warning, args.critical)
  File "./check_bareos.py", line 448, in checkEmptyTapes
    courser.execute(query)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '::INTERVAL)<now() and VolStatus not like 'Error')' at line 6")
```

**Comment by widhalmt** [comment]
I'm sorry, I don't have the resources to reproduce the error right now. I'll find more team members to work on it. Sorry for the inconvenience.

**Comment by martialblog** [comment]
Hi, if the issue still persists please check out the latest release. 

Have a good one
